#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

cp $TEST_DIR/../../../../../Tests/EndToEndTests/Simple2d/Data/SimpleDataTrain_cntk_text.txt $TEST_DIR || exit $?
if [ "$OS" == "Windows_NT" ]; then  
  pushd $TEST_BIN_DIR > /dev/null
else
  pushd $TEST_BIN_DIR/../lib > /dev/null
fi 
dotnet CNTKLibraryCSTrainingTest.dll SimpleFeedForwardClassifierTest
popd > /dev/null

ExitCode=$?

exit $ExitCode
