#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

if [ "$OS" == "Windows_NT" ]; then
  pushd $TEST_BIN_DIR > /dev/null
else
  pushd $TEST_BIN_DIR/../lib > /dev/null
fi
dotnet CNTKLibraryCSTrainingTest.dll MNISTClassifierTest
popd > /dev/null

ExitCode=$?

exit $ExitCode
